version: "3"

services:
  nexus:
    container_name: nexus
    privileged: true
    restart: always
    image: sonatype/nexus3
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "/opt/docker/volumes/nexus/data:/nexus-data"
