version: "2"

services:
  sonarqube:
    image: sonarqube:6.7.1
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonarqube
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    volumes:
      - /opt/docker/volumes/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - /opt/docker/volumes/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /opt/docker/volumes/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - db
    networks:
      - sonarnet

  db:
    image: postgres:9.6
    container_name: sonarqube-db
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    volumes:
      - /opt/docker/volumes/sonarqube/postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge
