version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    privileged: true
    restart: always
    hostname: 'gitlab.heylinux.com'
    environment
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.heylinux.com:8080'
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "sender@heylinux.com"
        gitlab_rails['smtp_password'] = "password"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'sender@heylinux.com'
        gitlab_rails['smtp_domain'] = "exmail.qq.com"
    ports:
      - '8080:8080'
      - '8022:8022'
    volumes:
      - '/opt/docker/volumes/gitlab/config:/etc/gitlab'
      - '/opt/docker/volumes/gitlab/logs:/var/log/gitlab'
      - '/opt/docker/volumes/gitlab/data:/var/opt/gitlab'
