version: "3"

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass password --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "/opt/docker/volumes/redis/data:/data"
